### ISSUE TITLE
Updating Global Outbound Routes with a From and To Prefix doesn't work

### ISSUE THREAD

**Issue by mackhendricks** [dOpensource/dsiprouter#163]
Updating the gateway list doesn't actually update the gateway list - no error is provided

**Comment by mackhendricks** [comment]
This problem was found in version 0.522

**Comment by jbarfield** [comment]
I am finding that this is still occurring in 0.524 which I am assuming is master after observing the code branches on the main github page. I cannot edit an existing route that has From/To Prefix data in order to change a gateway or a priority. However I can delete the route and install a new route. Could this be a regression? If I switch to .523 will the fix from 6/27/19 mentioned in this bug report apply?

**Comment by mackhendricks** [comment]
We will look at this.

**Comment by RichSosa28** [comment]
Closing this issue because it is no longer valid.
