### ISSUE TITLE
"Glitch" with the changes to reply after INVITE in version 0.522

### ISSUE THREAD

**Issue by Noksee** [dOpensource/dsiprouter#180]
I uncovered a "glitch" that I think comes from this change: 
_Added support for handling Inbound DID's when a Primary PBX/Endpoint or Secondary PBX/Endpoint doesn't reply after an INVITE. We added a value that times out the INVITE based on a global value._
Basically, if a call is sent from dSIP to a PBX and the PBX forwards that call to an outbound number, it cuts the call after about 5 seconds. To fix it, (in FreePBX anyways), you have to set the _Force Answer_ option to _Yes_ under the advanced tab of an inbound route.

**Comment by devopsec** [comment]
This should be fixed by commit a15d049d16a32896d73267da550d8f2826518526
We made the timeout follow more closely rfc 3261, changing it to 32 seconds
Please refer to Table 4, https://tools.ietf.org/html/rfc3261#page-264
For some people this may be too long or for some PBX's they may need additional configuring, such as aggressive reply modes like you stated.
Let us know if this is successful for your use case while we keep testing with this
