### ISSUE TITLE
Full Support for IPv6

### ISSUE THREAD

**Issue by devopsec** [dOpensource/dsiprouter#192]
Currently we don't have full support for ipv6, and are defaulting to ipv4
To accomplish this we need the following:

- option to enable ipv6 in install script
- update settings.py to have configurable ipv6 variable
- update shared.py to use similar ipv6 logic that is in dsip_lib.sh [see getExternalIP()]
- update kamailio.cfg to support bridging ipv4 and ipv6 and routing between the two
- update rtpengine config to support bridging ipv4 and ipv6

Some preliminary research:

- kamailio
https://stackoverflow.com/questions/55629076/how-to-configure-ipv6-in-kamailio
https://github.com/kamailio/kamailio/blob/master/src/modules/rtpproxy/examples/4to6.cfg
https://kb.asipto.com/kamailio:kamailio-mixed-ipv4-ipv6

- rtpengine
https://voipmagazine.wordpress.com/tag/ipv6/
https://ananddayal.blogspot.com/2017/10/kamailio-rtpengine-ipv6-ipv4.html

**Comment by devopsec** [comment]
in testing phase, see commit: 287e9f6759b3d18f48dbf6ca170fa48be2b00c82

**Comment by mackhendricks** [comment]
@devopsec I see that the EXTERNAL_IP field inside /etc/dsiprouter/gui/settings.py is set to1.1.1.1

This is what i see below.  We need that value to be correct since we use it for other stuff such as FusionPBX integration

# updated dynamically! These values will be overwritten
IPV6_ENABLED = False
INTERNAL_IP_ADDR = '192.168.0.1'
INTERNAL_IP_NET = '192.168.0.1/24'
INTERNAL_IP6_ADDR = '2604:a880:400:d0::2048:3001'
INTERNAL_IP6_NET = '2604:a880:400:d0::2048:3001/64'
**EXTERNAL_IP_ADDR = '1.1.1.1'**
EXTERNAL_IP6_ADDR = '2604:a880:400:d0::2048:3001'
EXTERNAL_FQDN = 'sip.dsiprouter.org'
