### ISSUE TITLE
Change Database URL to remote sql server

### ISSUE THREAD

**Issue by jzrlost** [dOpensource/dsiprouter#307]
Just installed the latest and greatest version (0.64).  In the past we have been able to change the kamailio.cfg file to point to our remote database.  Now when we try to change settings in that file the program bombs.  We then tried to use the setkamdbconfig command line and it fails to connect to the remote database.  When we debug setkamdbconfig it shows trying to connect to the remote database using the root username and no password.  The root mysql user will not connect remotely without a password.

**Comment by RichSosa28** [comment]
Hello,
We are working on this issue now and will get back to you with a solution soon.

**Comment by mackhendricks** [comment]
This issue has been validated.  You can reproduce this issue using the following steps:

1. Install dSIPRouter
2. Install MySQL/Mariadb on a separate system
3. Make MySQL listen on an external IP address (by default it only listens on localhost)
```
 sed -i "s/.*bind-address.*/bind-address = 0.0.0.0/" /etc/mysql/mariadb.conf.d/50-server.cnf
```
4. Export the kamailio database from dSIPRouter
 ```
mysqldump kamailio > kamailio.sql
```
5. Setup the Kamailio database on the remote system by executing these commands
```
mysql -e "create database kamailio"
mysql -e "CREATE USER 'kamailio'@'%' IDENTIFIED BY 'kamailio123'"
mysql -e "GRANT ALL PRIVILEGES ON kamailio.* TO 'kamailio'@'%'"
mysql -e "GRANT ALL PRIVILEGES ON kamailio.* TO 'kamailio'@'localhost'"
mysql -e "flush privileges"
```
6. Execute the dSIPRouter command to change the Kamailio database info.  This command is needed because the password in the settings.py is now encrypted.  This command should safely change these setting 
```
dsiprouter setkamdbconfig -debug kamailio:kamailio123@206.189.188.228:3306/kamailio
```
When running the command in debug mode we can see that the root user is being used to validate that the kamailio database exists in the remote database (see attached image).  However, we don't have the root credentials to the remote database, so that fails.   If this did work, we also try to change the kamailio credentials in the remote database - that would fail as well because we don't have the root user.  Basically, we are assuming the database is running locally.  

I propose that we add a parameters that allow users to specify the MySQL user and password with the proper privileges to create or update the user [ note - we should not assume the root username is "root" ].  We should also have a flag that will create the database in the remote system by exporting the local kamailio database and importing it to the remote server.  This will save users time when setting up dSIPRouter with a remote database.  
 
![image](https://user-images.githubusercontent.com/5568984/100860305-56a29d80-345e-11eb-93e9-8155eca776ee.png)

**Comment by devopsec** [comment]
# Expanded Instructions

## on remote db host

```
apt update -y
apt install -y mariadb-server mariadb-client
sed -i "s/.*bind-address.*/bind-address = 0.0.0.0/" /etc/mysql/mariadb.conf.d/50-server.cnf
systemctl restart mysql
mysql -e "CREATE DATABASE kamailio;"
mysql -e "CREATE USER 'kamailio'@'localhost' IDENTIFIED BY 'kamailio123';"
mysql -e "CREATE USER 'kamailio'@'%' IDENTIFIED BY 'kamailio123';"
mysql -e "GRANT ALL PRIVILEGES ON kamailio.* TO 'kamailio'@'%';"
mysql -e "GRANT ALL PRIVILEGES ON kamailio.* TO 'kamailio'@'localhost';"
mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'root123';"
cat << EOF > ~/.my.cnf
[client]
user=root
password=root123
EOF
mysql -e "CREATE USER 'root'@'%' IDENTIFIED BY 'root123';"
mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'root123';"
mysql -e "FLUSH PRIVILEGES;"
```

## on dsiprouter host

```
REMOTE_DB_HOST='68.183.61.232'
apt update -y
apt install -y git
git clone -b v0.641 https://github.com/dOpensource/dsiprouter.git /opt/dsiprouter
/opt/dsiprouter/dsiprouter.sh install -debug -all -db kamailio:kamailio123@${REMOTE_DB_HOST}:3306/kamailio -dbadmin root:root123/mysql
```

#### or with the setkamdbconfig command...

```
REMOTE_DB_HOST='68.183.61.232'
apt update -y
apt install -y git
git clone -b v0.641 https://github.com/dOpensource/dsiprouter.git /opt/dsiprouter
/opt/dsiprouter/dsiprouter.sh install -debug -all
dsiprouter setkamdbconfig -debug -dbadmin root:root123/mysql kamailio:kamailio123@${REMOTE_DB_HOST}:3306/kamailio
```

**Comment by devopsec** [comment]
DB tables not created on remote DB on fresh install.  
It should function the same as local DB install:  
- if kamailio DB exists backup DB and drop
- create fresh DB and configure as normal

**Comment by devopsec** [comment]
`setkamdbconfig` command removed and the logic moved to `setcredentials` as such:  

```
dsiprouter setcrednetials -debug -dac root:root123/mysql -kc kamailio:kamailio123@${REMOTE_DB_HOST}:3306/kamailio
```

**Comment by devopsec** [comment]
Ref WIP Commit f80ef93a71dff7ae697bff7264a3cebf74c28163  
Auth is failing to remote db, need more testing

**Comment by jzrlost** [comment]
Installed branch 0.641 to do some testing with the new remote database programming and everything seems to install fine, but the webpage gives me a 502 bad gateway.  After rebooting the server in the CLI it shows a different IP address to connect to the web gui, but not sure where that IP came from since after the install all the the IP addresses showed correctly.  The IP comes back as a DigitalOcean IP which from what I know it not my IP address.  Not sure what or where it's picking this IP address up from.

**Comment by mackhendricks** [comment]
That release is going through integration.

**Comment by jzrlost** [comment]
Ok...I'll wait to test.  Thanks for the quick reply.

**Comment by mackhendricks** [comment]
I think we tried to cover to much ground on this issue.  The main intent of this issue was to support changing the DB URL to use a remote database.  But, the commit also covers installing dSIPRouter to a remote database on install.  I will open another issue to capture that use case.  I have confirmed that using the setcredentials subcommand you can change the DB URL

 dsiprouter setcredentials -kc kamailio:kamailiorw100@terraform-20210201213031041000000002.cjn4ivwosjda.us-east-1.rds.amazonaws.com:3306/kamailio

**Comment by devopsec** [comment]
I believe the intent was filled on this issue.  
When installing dSIPRouter (in every use case) it is expected that the kamailio DB will be created from scratch (we never use a pre-formatted DB on install).  
Cluster install currently does not support reusing the same DB on install (it will be reformatted after each install process on each node) if that is what you are asking.

**Comment by jzrlost** [comment]
We aren't looking for the remote database to be filled during install if that makes a difference.  How we are using Dsiprouter now with .523 is we have 1 Dsiprouter that uses the local database (dsip-db), we make all changes on this machine only.  Then we have 4 other Dsiprouters (2 incoming and 2 outgoing daisy changed in asterisk for redundancy) that connect/read the database on the 1 machine (dsip-db) to pull the database info or at least read and use the info (centralized database for read only purposes).  We don't make any changes on the 4 Dsiprouters and only use the button to "reload kamailio" when the database changes on the 1 machine (dsip-db).  The 4 Dsiprouters that use the remote database do not show any info in their webpages and this is fine.  Does that all make since?

It all works with .523 because we can update the kamailio.conf manually to use the database on the 1 main machine (dsip-db).  We couldn't do that in .641 since the info is encrypted now.  I will load up a few VMs today and test the command.  Thank you for everyone's hard work on this.

**Comment by jzrlost** [comment]
It seems that .641 is maybe not ready to be tested?  I installed the .641 branch and thought everything was ok.  Unfortunatly, the "setcredentials" command didn't change anything and after a reboot I got the 502 bad gateway error again.  Will the new "setcredentials" work on the .64 branch or is there any time frame on the .641 branch being ready?

**Comment by devopsec** [comment]
We are finishing up testing and validation on 0.641, you will  see the release in the releases section when it goes into production.

**Comment by jzrlost** [comment]
We loaded up 0.641 on all three machines and was able to get them all connected to the same remote database.  It took a few tries on the exact syntax to get it working, but it's working great.  Thank you, thank you.  We have moved a few of our asterisk servers over and so far so good.  Thank you again for all of the hard work that every puts into this software.
