### ISSUE TITLE
dsiprouter not listening

### ISSUE THREAD

**Issue by JohanPeeters12** [dOpensource/dsiprouter#35]
First, a little small installation bug in the script. It checks on 'wheezy' instead of 'jessie'.
After that installation runs fine.
But http server is not installed or not listening, so no way to get into dsiprouter.
Netstat -l --> nothing listening on 5000

**Comment by mackhendricks** [comment]
Thanks.   We will fix that.

What release are you using?

Can you do /.dsiprouter.sh stop

/.dsiprouter.sh start -debug

Please reply back with /var/log/dsiprouter.log

**Comment by JohanPeeters12** [comment]
Using debian jessie and gor dsiprouter from git as instructed, dont know which version that is.

The last line of the console is: 
+ nohup /usr/bin/python3.4m ./gui/dsiprouter.py runserver -h 0.0.0.0 -p 5000

The log shows only this info:
Traceback (most recent call last):
  File "./gui/dsiprouter.py", line 1, in <module>
    from flask import Flask, render_template, request, redirect, abort, flash, session, url_for
ImportError: No module named 'flask'

**Comment by JohanPeeters12** [comment]
So I had to install lots and lots of missing modules.
Done that and now getting missing table (qlalchemy.exc.NoSuchTableError: `dsip_fusionpbx_db`)

Also tried installing on debian stretch, but that one already giving lots and lots of errors during installation.
Probably because stretch only supports python3.5

Centos same story as jessie.

**Comment by mackhendricks** [comment]
I will fix the installer and give you an update in a few

**Comment by JohanPeeters12** [comment]
Ok, redone the whole thing in jessie.
I have installed those missing modules before installing dsiprouter and that looked promissing.
No errors in the logs this time, but no website.

After changing the hardcoded 0.0.0.0 in dsiprouting.sh to my internet address, I got the website and all looks fine so far :)

**Comment by mackhendricks** [comment]
Hey,

I fixed the master branch so that Stretch works.  So, please do a pull and then:

/dsiprouter.sh uninstall
./dsiprouter.sh install

We are only officially supporting Stretch for this release due to the new framework we put in place for installation.

Sorry about the install issues.  Please let me know how it goes.  I also created a short video that shows the install process on Debian Stretch 9.4: https://youtu.be/Iu4BQkL1wGc

ps.  We will be working on converting the existing Debian Jeesie install script to the new framework and testing it completely.  It taking more time then we expected :-)

**Comment by mackhendricks** [comment]
Closing ticket is was fixed in 0.34 release
