### ISSUE TITLE
Error at start of installation script

### ISSUE THREAD

**Issue by kristapsdravnieks** [dOpensource/dsiprouter#365]
first error message during install:

chown: invalid user: ‘dsiprouter:dsiprouter’
chown: invalid user: ‘dsiprouter:kamailio’
chown: invalid user: ‘dsiprouter:root’

**Comment by mackhendricks** [comment]
Which version of dSIPRouter and which OS version

**Comment by kristapsdravnieks** [comment]
Version 0.641 on Debian 9.13,
I tried to run install on debian 10 but it stopped right after adding /etc/apt/sources.list.d/official-releases.list file and broke apt.

**Comment by kristapsdravnieks** [comment]
The same:
chown: invalid user: ‘dsiprouter:dsiprouter’
chown: invalid user: ‘dsiprouter:kamailio’
chown: invalid user: ‘dsiprouter:root’
error apeared on centos 8 install.

**Comment by devopsec** [comment]
The updates to apt sources list is a workaround for some cloud providers' not having reliable debian repos.  
It does not break apt, but the workaround isn't perfect (you'll see some errors about duplicates that can be safely ignored).  

The `chown` issue as I mentioned is an issue effecting all OS versions and will be fixed in the upcoming v0.65 release.

**Comment by mackhendricks** [comment]
Kristaps,









 where is VM located?  Cloud provider, VM ware, etc

**Comment by arinaitwebrn** [comment]
> first error message during install:
> 
> chown: invalid user: ‘dsiprouter:dsiprouter’ chown: invalid user: ‘dsiprouter:kamailio’ chown: invalid user: ‘dsiprouter:root’

hey were you able to resolve this issue  ?
