### ISSUE TITLE
Misc Configuration information should be stored in a htable that's back by a DB table

### ISSUE THREAD

**Issue by mackhendricks** [dOpensource/dsiprouter#46]
All configuration is now stored in a flat file in [dsiprouter_home]/gui/settings.py.  

I'm proposing that we have basic database connection info and other node specific info in [dsiprouter_home]/gui/settings.py and all other info should be stored in a htable that's backed by a DB table.  This will allow us to implement use cases like:

- Specify per PBX/Endpoint information such as the number of concurrent dialogs allowed. 

We should design for Redis upfront so that it works with our DB of choice, which is MySQL, but should work with Redis.

**Comment by devopsec** [comment]
I think this is a deceivingly complex problem.
We need to consider 2 problems for this issue:

1. settings.py is imported by a vast majority of the python files.
Because this is the case when we move those settings to a DB every one of those files will either be forced to make a connection to the DB to get these settings,
Or.. we would have to come up with a structured way of bootstrapping those settings and sharing them globally to all the other python scripts

2. we have to consider HA implementation for any settings that are dynamic.
If the setting is dynamic an update in the DB would not propagate to the loaded HTables, we would have to create a system for loading and reloading these settings into HTables for currently running kamailio processes from the dsiprouter app.
We could possibly separate dynamic settings into a single HTable and update the values of those entries, but they would have to be triggered by any changes to the dynamic DB table, so possibly SQL Triggers / DDL events could help here.

Note that this is only considering loading the settings.py configs which would be completely different from loading the kamailio.cfg settings from DB (which we spoke of previously). That separate use case would probably be a good candidate for the cfg_db module: https://www.kamailio.org/docs/modules/5.1.x/modules/cfg_db.html
But that is a completely separate topic

**Comment by mackhendricks** [comment]
The agreed upon architecture consists of all of the [dsiprouter_home]/gui/settings.py values are stored in a database table called dsip_settings.  At some point in time we can have this table represented as a htable in Kamailio, which would make the values available during runtime without doing a database lookup.
