### ISSUE TITLE
Duplicate Inbound DID

### ISSUE THREAD

**Issue by matmurdock** [dOpensource/dsiprouter#77]
At the moment you can added duplicate DID's.  This shouldn't be allowed AFAIK.

Mat

**Comment by devopsec** [comment]
Thanks @matmurdock we will put this on the roadmap for v0.60

**Comment by mackhendricks** [comment]
This is being moved into 0.523.  We should add a RestFul API for adding DID's and place logic for giving an exception when we try to enter a duplicate.  The UI would need to to know how to deal with these exceptions, which at the minimum should tell the user that the DID is already being used.  We should support add, update and delete.  In order to make the cutoff for 0.523 let's just have the UI support adding using the API.  The update and delete can continue to use the existing logic.

mapping: {
          did: 1234567894
          servers: {
             primary: p1.pbx.com
             secondary: p2.pbx.com
 }

**Comment by mackhendricks** [comment]
The primary and secondary can be PBXID since we don't have away of converting pbx friendly names to PBXID as of right now

mapping: {
did: 1234567894
servers: {
primary: 65
secondary: 64
}
