### ISSUE TITLE
Inbound issues with FusionPBX

### ISSUE THREAD

**Issue by gunemalli** [dOpensource/dsiprouter#91]
Hi Team,

Just running some tests with hosted PBX we have via FusionPBX. The setup is as follows:

Carriers -> FusionPBX <- dSIPRouter <- Handset/Softphone.

What works:

- Registrations
- Outbound Calls
- Extension to Extension
- Presence
- Transfers

The problem we're having at the moment is with inbound external calls. The call comes into the hosted PBX directly (not via dsiprouter) and the PBX passes the INVITE to dSIPRouter. However, instead of passing the INVITE back to the endpoint, dSIPRouter router send a proxy auth request.

Can you help me with setting this up correctly to forward the invite request to endpoint?

Kind Regards,
Asanka

**Comment by gunemalli** [comment]
Hi,

Yes, I've enabled FusioPBX support as mentioned in the guide.

![image](https://user-images.githubusercontent.com/33611000/49733400-5aecb380-fca7-11e8-80de-c74ef328fdf5.png)

**Comment by mackhendricks** [comment]
What version of dSIPRouter are your using?

Let's turn on Kamailio logging to see what's going on.  Do the following:

1) echo local0.*     -/var/log/kamailio > /etc/rsyslog.d/kamailio.conf
2) systemctl restart rsyslog
3) vi /etc/kamailio/kamailio.cfg
change 
##!define WITH_DEBUG
to:
#!define WITH_DEBUG

4) systemctl restart kamailio

Send me the log at support@dopensource.com since it might contain IP's and stuff in it.

**Comment by mackhendricks** [comment]
Closing this ticket because it was a network related issue per @gunemalli
